global:
  nothing: nothing

editor:
  # initial frame size (the data is normalized to -100, 100 on wider axis)
  init_xlim_low: -190
  init_xlim_high: 190
  init_ylim_low: -150
  init_ylim_high: 150

  # initial font size
  font_size: 10
  label_bbox:
    # for possible dictionary arguments refer to 
    # https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.FancyBboxPatch.html#matplotlib.patches.FancyBboxPatch
    boxstyle: round
    pad: 0.2
    facecolor: white
    edgecolor: black


labels_generator:

  data_processing:
    merge_parametrized_labels: True

  configurations:
    iterative:
      maxiter: 100
      visit: 2.62
      initial_temp: 5230
      restart_temp_ratio: 0.00002
      accept: -5
      no_local_search: True

    global:
      generate_greedy_x0: True
      maxiter: 100
      visit: 2.62
      initial_temp: 5230
      restart_temp_ratio: 0.00002
      accept: -5
      no_local_search: True

    divide_and_conquare:
      maxiter: 100
      visit: 2.62
      initial_temp: 5230
      restart_temp_ratio: 0.00002
      accept: -5
      no_local_search: True

    timed:
      time: 5  #s
