name: Pylint

on:
  pull_request:
    branches:
      - master

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Analysing the code with pylint
        run: |
          pylint --disable=C,R src > pylint_output.txt || true

      - name: Extract score
        run: |
          SCORE=$(grep 'Your code has been rated at ' pylint_output.txt | cut -d' ' -f6 | xargs)
          echo "Pylint Score: $SCORE" > pylint_score.txt

      - name: Post Pylint score as a pull request review comment
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const score = fs.readFileSync('pylint_score.txt', 'utf8').trim();
            const context = github.context;
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            octokit.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'COMMENT',
              body: `${score}`
            });